/*
 * Generated by gdbus-codegen 2.30.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __NEARD_MANAGER_PROXY_H__
#define __NEARD_MANAGER_PROXY_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.neard.Manager */

#define ORG_NEARD_MGR_TYPE_ (org_neard_mgr__get_type ())
#define ORG_NEARD_MGR_(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORG_NEARD_MGR_TYPE_, orgNeardMgr))
#define ORG_NEARD_MGR_IS_(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORG_NEARD_MGR_TYPE_))
#define ORG_NEARD_MGR__GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ORG_NEARD_MGR_TYPE_, orgNeardMgrIface))

struct _orgNeardMgr;
typedef struct _orgNeardMgr orgNeardMgr;
typedef struct _orgNeardMgrIface orgNeardMgrIface;

struct _orgNeardMgrIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_properties) (
    orgNeardMgr *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_property) (
    orgNeardMgr *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);

  void (*adapter_added) (
    orgNeardMgr *object,
    const gchar *arg_unnamed_arg0);

  void (*adapter_removed) (
    orgNeardMgr *object,
    const gchar *arg_unnamed_arg0);

  void (*property_changed) (
    orgNeardMgr *object,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);

};

GType org_neard_mgr__get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_neard_mgr__interface_info (void);
guint org_neard_mgr__override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_neard_mgr__complete_get_properties (
    orgNeardMgr *object,
    GDBusMethodInvocation *invocation,
    GVariant *unnamed_arg0);

void org_neard_mgr__complete_set_property (
    orgNeardMgr *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void org_neard_mgr__emit_property_changed (
    orgNeardMgr *object,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);

void org_neard_mgr__emit_adapter_added (
    orgNeardMgr *object,
    const gchar *arg_unnamed_arg0);

void org_neard_mgr__emit_adapter_removed (
    orgNeardMgr *object,
    const gchar *arg_unnamed_arg0);



/* D-Bus method calls: */
void org_neard_mgr__call_get_properties (
    orgNeardMgr *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_neard_mgr__call_get_properties_finish (
    orgNeardMgr *proxy,
    GVariant **out_unnamed_arg0,
    GAsyncResult *res,
    GError **error);

gboolean org_neard_mgr__call_get_properties_sync (
    orgNeardMgr *proxy,
    GVariant **out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error);

void org_neard_mgr__call_set_property (
    orgNeardMgr *proxy,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_neard_mgr__call_set_property_finish (
    orgNeardMgr *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_neard_mgr__call_set_property_sync (
    orgNeardMgr *proxy,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define ORG_NEARD_MGR_TYPE__PROXY (org_neard_mgr__proxy_get_type ())
#define ORG_NEARD_MGR__PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORG_NEARD_MGR_TYPE__PROXY, orgNeardMgrProxy))
#define ORG_NEARD_MGR__PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORG_NEARD_MGR_TYPE__PROXY, orgNeardMgrProxyClass))
#define ORG_NEARD_MGR__PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORG_NEARD_MGR_TYPE__PROXY, orgNeardMgrProxyClass))
#define ORG_NEARD_MGR_IS__PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORG_NEARD_MGR_TYPE__PROXY))
#define ORG_NEARD_MGR_IS__PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORG_NEARD_MGR_TYPE__PROXY))

typedef struct _orgNeardMgrProxy orgNeardMgrProxy;
typedef struct _orgNeardMgrProxyClass orgNeardMgrProxyClass;
typedef struct _orgNeardMgrProxyPrivate orgNeardMgrProxyPrivate;

struct _orgNeardMgrProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  orgNeardMgrProxyPrivate *priv;
};

struct _orgNeardMgrProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_neard_mgr__proxy_get_type (void) G_GNUC_CONST;

void org_neard_mgr__proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
orgNeardMgr *org_neard_mgr__proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
orgNeardMgr *org_neard_mgr__proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_neard_mgr__proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
orgNeardMgr *org_neard_mgr__proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
orgNeardMgr *org_neard_mgr__proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define ORG_NEARD_MGR_TYPE__SKELETON (org_neard_mgr__skeleton_get_type ())
#define ORG_NEARD_MGR__SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORG_NEARD_MGR_TYPE__SKELETON, orgNeardMgrSkeleton))
#define ORG_NEARD_MGR__SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORG_NEARD_MGR_TYPE__SKELETON, orgNeardMgrSkeletonClass))
#define ORG_NEARD_MGR__SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORG_NEARD_MGR_TYPE__SKELETON, orgNeardMgrSkeletonClass))
#define ORG_NEARD_MGR_IS__SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORG_NEARD_MGR_TYPE__SKELETON))
#define ORG_NEARD_MGR_IS__SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORG_NEARD_MGR_TYPE__SKELETON))

typedef struct _orgNeardMgrSkeleton orgNeardMgrSkeleton;
typedef struct _orgNeardMgrSkeletonClass orgNeardMgrSkeletonClass;
typedef struct _orgNeardMgrSkeletonPrivate orgNeardMgrSkeletonPrivate;

struct _orgNeardMgrSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  orgNeardMgrSkeletonPrivate *priv;
};

struct _orgNeardMgrSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_neard_mgr__skeleton_get_type (void) G_GNUC_CONST;

orgNeardMgr *org_neard_mgr__skeleton_new (void);


G_END_DECLS

#endif /* __NEARD_MANAGER_PROXY_H__ */
