/*
 * Generated by gdbus-codegen 2.30.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __NEARD_TARGET_PROXY_H__
#define __NEARD_TARGET_PROXY_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.neard.Target */

#define ORG_NEARD_TGT_TYPE_ (org_neard_tgt__get_type ())
#define ORG_NEARD_TGT_(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORG_NEARD_TGT_TYPE_, orgNeardTgt))
#define ORG_NEARD_TGT_IS_(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORG_NEARD_TGT_TYPE_))
#define ORG_NEARD_TGT__GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ORG_NEARD_TGT_TYPE_, orgNeardTgtIface))

struct _orgNeardTgt;
typedef struct _orgNeardTgt orgNeardTgt;
typedef struct _orgNeardTgtIface orgNeardTgtIface;

struct _orgNeardTgtIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_properties) (
    orgNeardTgt *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_property) (
    orgNeardTgt *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);

  void (*property_changed) (
    orgNeardTgt *object,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);

};

GType org_neard_tgt__get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_neard_tgt__interface_info (void);
guint org_neard_tgt__override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_neard_tgt__complete_get_properties (
    orgNeardTgt *object,
    GDBusMethodInvocation *invocation,
    GVariant *unnamed_arg0);

void org_neard_tgt__complete_set_property (
    orgNeardTgt *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void org_neard_tgt__emit_property_changed (
    orgNeardTgt *object,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1);



/* D-Bus method calls: */
void org_neard_tgt__call_get_properties (
    orgNeardTgt *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_neard_tgt__call_get_properties_finish (
    orgNeardTgt *proxy,
    GVariant **out_unnamed_arg0,
    GAsyncResult *res,
    GError **error);

gboolean org_neard_tgt__call_get_properties_sync (
    orgNeardTgt *proxy,
    GVariant **out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error);

void org_neard_tgt__call_set_property (
    orgNeardTgt *proxy,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_neard_tgt__call_set_property_finish (
    orgNeardTgt *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_neard_tgt__call_set_property_sync (
    orgNeardTgt *proxy,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define ORG_NEARD_TGT_TYPE__PROXY (org_neard_tgt__proxy_get_type ())
#define ORG_NEARD_TGT__PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORG_NEARD_TGT_TYPE__PROXY, orgNeardTgtProxy))
#define ORG_NEARD_TGT__PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORG_NEARD_TGT_TYPE__PROXY, orgNeardTgtProxyClass))
#define ORG_NEARD_TGT__PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORG_NEARD_TGT_TYPE__PROXY, orgNeardTgtProxyClass))
#define ORG_NEARD_TGT_IS__PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORG_NEARD_TGT_TYPE__PROXY))
#define ORG_NEARD_TGT_IS__PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORG_NEARD_TGT_TYPE__PROXY))

typedef struct _orgNeardTgtProxy orgNeardTgtProxy;
typedef struct _orgNeardTgtProxyClass orgNeardTgtProxyClass;
typedef struct _orgNeardTgtProxyPrivate orgNeardTgtProxyPrivate;

struct _orgNeardTgtProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  orgNeardTgtProxyPrivate *priv;
};

struct _orgNeardTgtProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_neard_tgt__proxy_get_type (void) G_GNUC_CONST;

void org_neard_tgt__proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
orgNeardTgt *org_neard_tgt__proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
orgNeardTgt *org_neard_tgt__proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_neard_tgt__proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
orgNeardTgt *org_neard_tgt__proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
orgNeardTgt *org_neard_tgt__proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define ORG_NEARD_TGT_TYPE__SKELETON (org_neard_tgt__skeleton_get_type ())
#define ORG_NEARD_TGT__SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORG_NEARD_TGT_TYPE__SKELETON, orgNeardTgtSkeleton))
#define ORG_NEARD_TGT__SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORG_NEARD_TGT_TYPE__SKELETON, orgNeardTgtSkeletonClass))
#define ORG_NEARD_TGT__SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORG_NEARD_TGT_TYPE__SKELETON, orgNeardTgtSkeletonClass))
#define ORG_NEARD_TGT_IS__SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORG_NEARD_TGT_TYPE__SKELETON))
#define ORG_NEARD_TGT_IS__SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORG_NEARD_TGT_TYPE__SKELETON))

typedef struct _orgNeardTgtSkeleton orgNeardTgtSkeleton;
typedef struct _orgNeardTgtSkeletonClass orgNeardTgtSkeletonClass;
typedef struct _orgNeardTgtSkeletonPrivate orgNeardTgtSkeletonPrivate;

struct _orgNeardTgtSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  orgNeardTgtSkeletonPrivate *priv;
};

struct _orgNeardTgtSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_neard_tgt__skeleton_get_type (void) G_GNUC_CONST;

orgNeardTgt *org_neard_tgt__skeleton_new (void);


G_END_DECLS

#endif /* __NEARD_TARGET_PROXY_H__ */
